
CREATE TABLE IF NOT EXISTS `datacrawl`.`interest_rate` (
  `MARKET_ID` VARCHAR(36) NOT NULL,
  `INT_RATE_TYPE` VARCHAR(20) NOT NULL,
  `YYYYMMDD` DATE NOT NULL,
  `INT_RATE` DOUBLE NOT NULL,
  PRIMARY KEY (`MARKET_ID`, `YYYYMMDD`, `INT_RATE_TYPE`),
  CONSTRAINT `fk_treasure_bond_int_rate_market1`
    FOREIGN KEY (`MARKET_ID`)
    REFERENCES `datacrawl`.`market` (`MARKET_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

