
CREATE TABLE IF NOT EXISTS `datacrawl`.`FINANCIAL_SHEET` (
  `FINANCIAL_SHEET_ID` VARCHAR(36) NOT NULL,
  `STOCK_ID` VARCHAR(36) NOT NULL,
  `YEAR` SMALLINT NOT NULL,
  `QUARTER` TINYINT NOT NULL COMMENT '0 : 연간 1,2,3,4 : 분기',
  `FINANCIAL_SHEET_TYPE` TINYINT NOT NULL COMMENT '0: 주요재무정보 1:대차대조표 2:현금흐름표 3:손익계산서 (IFRS연결만 취급)',
  `ESTIMATED_SHEET` TINYINT NOT NULL COMMENT '추정재무제표여부',
  `CREATED_DATE` TIMESTAMP NOT NULL,
  PRIMARY KEY (`FINANCIAL_SHEET_ID`),
  INDEX `fk_FINANCIAL_SHEET_STOCK1_idx` (`STOCK_ID` ASC),
  CONSTRAINT `fk_FINANCIAL_SHEET_STOCK1`
    FOREIGN KEY (`STOCK_ID`)
    REFERENCES `datacrawl`.`STOCK` (`STOCK_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `datacrawl`.`FINANCIAL_SHEET_TERM` (
  `FINANCIAL_SHEET_TERM_ID` VARCHAR(36) NOT NULL,
  `REPRESENT_TERM` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`FINANCIAL_SHEET_TERM_ID`),
  UNIQUE INDEX `TERM_UNIQUE` (`REPRESENT_TERM` ASC))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `datacrawl`.`FINANCIAL_SHEET_ITEM` (
  `FINANCIAL_SHEET_ID` VARCHAR(36) NOT NULL,
  `FINANCIAL_SHEET_TERM_ID` VARCHAR(36) NOT NULL,
  `VALUE` INT NOT NULL,
  `CREATED_DATE` TIMESTAMP NOT NULL,
  PRIMARY KEY (`FINANCIAL_SHEET_ID`, `FINANCIAL_SHEET_TERM_ID`),
  INDEX `fk_FINANCIAL_SHEET_ITEM_FINANCIAL_SHEET_TERM2_idx` (`FINANCIAL_SHEET_TERM_ID` ASC),
  CONSTRAINT `fk_FINANCIAL_SHEET_ITEM_FINANCIAL_SHEET2`
    FOREIGN KEY (`FINANCIAL_SHEET_ID`)
    REFERENCES `datacrawl`.`FINANCIAL_SHEET` (`FINANCIAL_SHEET_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FINANCIAL_SHEET_ITEM_FINANCIAL_SHEET_TERM2`
    FOREIGN KEY (`FINANCIAL_SHEET_TERM_ID`)
    REFERENCES `datacrawl`.`FINANCIAL_SHEET_TERM` (`FINANCIAL_SHEET_TERM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `datacrawl`.`FINANCIAL_SHEET_TERM_TEXT` (
  `FINANCIAL_SHEET_TERM_ID` VARCHAR(36) NOT NULL,
  `TERM_TEXT` VARCHAR(45) NOT NULL COMMENT '크롤링 소스에 따라 같은 것을 다르게 표현할 수 있음. 같은 것을 뜻하는 텍스트 목록을 저장. whitespace, 특수문자 제거',
  INDEX `fk_FINANCIAL_SHEET_TERM_TEXT_FINANCIAL_SHEET_TERM1_idx` (`FINANCIAL_SHEET_TERM_ID` ASC),
  PRIMARY KEY (`TERM_TEXT`, `FINANCIAL_SHEET_TERM_ID`),
  CONSTRAINT `fk_FINANCIAL_SHEET_TERM_TEXT_FINANCIAL_SHEET_TERM1`
    FOREIGN KEY (`FINANCIAL_SHEET_TERM_ID`)
    REFERENCES `datacrawl`.`FINANCIAL_SHEET_TERM` (`FINANCIAL_SHEET_TERM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

