
drop table if exists datacrawl.financial_sheet_item;
drop table if exists datacrawl.financial_sheet_term_text;
drop table if exists datacrawl.financial_sheet_term;

CREATE TABLE IF NOT EXISTS `datacrawl`.`FINANCIAL_SHEET_TERM` (
  `TERM` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`TERM`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `datacrawl`.`FINANCIAL_SHEET_ITEM` (
  `FINANCIAL_SHEET_ID` VARCHAR(36) NOT NULL,
  `TERM` VARCHAR(36) NOT NULL,
  `VALUE` INT NOT NULL,
  `CREATED_DATE` TIMESTAMP NOT NULL,
  PRIMARY KEY (`FINANCIAL_SHEET_ID`, `TERM`),
  INDEX `fk_FINANCIAL_SHEET_ITEM_FINANCIAL_SHEET_TERM2_idx` (`TERM` ASC),
  CONSTRAINT `fk_FINANCIAL_SHEET_ITEM_FINANCIAL_SHEET2`
    FOREIGN KEY (`FINANCIAL_SHEET_ID`)
    REFERENCES `datacrawl`.`FINANCIAL_SHEET` (`FINANCIAL_SHEET_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FINANCIAL_SHEET_ITEM_FINANCIAL_SHEET_TERM2`
    FOREIGN KEY (`TERM`)
    REFERENCES `datacrawl`.`FINANCIAL_SHEET_TERM` (`TERM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

